#ifndef _PRODUCTION_H_
#define _PRODUCTION_H_

typedef enum Production {
  TERM_IDENTIFIER,
  TERM_CONSTANT,
  TERM_STRING_LITERAL,

  PROD_PRIMARY_IDENTIFIER,
  PROD_PRIMARY_CONSTANT,
  PROD_PRIMARY_STRING,

  PROD_POSTFIX_ARRAYREF,
  PROD_POSTFIX_INVOKE_VOID,
  PROD_POSTFIX_INVOKE_ARGS,
  PROD_POSTFIX_FIELDREF,
  PROD_POSTFIX_PTRFIELDREF,
  PROD_POSTFIX_INC,
  PROD_POSTFIX_DEC,

  PROD_ARG_LIST_CONV,
  PROD_ARG_LIST_REC,

  PROD_PREFIX_INC,
  PROD_PREFIX_DEC,
  PROD_PREFIX_ADDR,
  PROD_PREFIX_DEREF,
  PROD_PREFIX_PLUS,
  PROD_PREFIX_MINUS,
  PROD_PREFIX_BITW_NOT,
  PROD_PREFIX_LOGIC_NOT,
  PROD_PREFIX_SIZEOF_EXPR,
  PROD_PREFIX_SIZEOF_TYPE,

  PROD_CAST,

  PROD_MUL,
  PROD_DIV,
  PROD_MOD,

  PROD_ADD,
  PROD_SUB,

  PROD_SHIFT_LEFT,
  PROD_SHIFT_RIGHT,

  PROD_RELA_LT,
  PROD_RELA_GT,
  PROD_RELA_LE,
  PROD_RELA_GE,

  PROD_RELA_EQ,
  PROD_RELA_NE,

  PROD_BITW_AND,

  PROD_BITW_XOR,

  PROD_BITW_OR,

  PROD_LOGIC_AND,

  PROD_LOGIC_OR,

  PROD_COND_TERN,

  PROD_ASSIGN_BASIC,
  PROD_ASSIGN_MUL,
  PROD_ASSIGN_DIV,
  PROD_ASSIGN_MOD,
  PROD_ASSIGN_ADD,
  PROD_ASSIGN_SUB,
  PROD_ASSIGN_LEFT,
  PROD_ASSIGN_RIGHT,
  PROD_ASSIGN_AND,
  PROD_ASSIGN_XOR,
  PROD_ASSIGN_OR,

  PROD_EXPR_SEPARATED,

  PROD_CONST_EXPR,

  PROD_TOTAL_COUNT
} Production;

extern void (**production_callback)(int production_type);
extern char* production_names[];
extern void initialize_productions_table(void);

#endif