rm test/generator/test/test000.txt
rm test/generator/test/output000.txt
rm test/generator/test/test001.txt
rm test/generator/test/output001.txt
rm test/generator/test/test002.txt
rm test/generator/test/output002.txt
rm test/generator/test/test003.txt
rm test/generator/test/output003.txt
rm test/generator/test/test004.txt
rm test/generator/test/output004.txt
rm test/generator/test/test005.txt
rm test/generator/test/output005.txt
rm test/generator/test/test006.txt
rm test/generator/test/output006.txt
rm test/generator/test/test007.txt
rm test/generator/test/output007.txt
rm test/generator/test/test008.txt
rm test/generator/test/output008.txt
rm test/generator/test/test009.txt
rm test/generator/test/output009.txt
rm test/generator/test/test010.txt
rm test/generator/test/output010.txt
rm test/generator/test/test011.txt
rm test/generator/test/output011.txt
rm test/generator/test/test012.txt
rm test/generator/test/output012.txt
rm test/generator/test/test013.txt
rm test/generator/test/output013.txt
rm test/generator/test/test014.txt
rm test/generator/test/output014.txt
rm test/generator/test/test015.txt
rm test/generator/test/output015.txt
