build/compiler test/semantic/test/test000.c > test/semantic/test/output000.txt
build/compiler test/semantic/test/test001.c > test/semantic/test/output001.txt
build/compiler test/semantic/test/test002.c > test/semantic/test/output002.txt
build/compiler test/semantic/test/test003.c > test/semantic/test/output003.txt
build/compiler test/semantic/test/test004.c > test/semantic/test/output004.txt
build/compiler test/semantic/test/test005.c > test/semantic/test/output005.txt
build/compiler test/semantic/test/test006.c > test/semantic/test/output006.txt
build/compiler test/semantic/test/test007.c > test/semantic/test/output007.txt
build/compiler test/semantic/test/test008.c > test/semantic/test/output008.txt
build/compiler test/semantic/test/test009.c > test/semantic/test/output009.txt
